/* eslint-disable */
/* tslint:disable */
import {ImageURISource} from "react-native";

/**
 * This file is auto-generated by react-native-image-resource-generator
 * !!! DO NOT EDIT !!!
 * For more information check the documentation:
 * https://github.com/svbutko/react-native-image-resource-generator
*/

export class ImageResources {
  static readonly camera: ImageURISource = require("../../resources/images/camera.png");
}