export enum Commerce {
    bag = "􀍣",
    bagBadgeMinus = "􀍧",
    bagBadgePlus = "􀍥",
    bagCircle = "􀒫",
    bagCircleFill = "􀒬",
    bagFill = "􀍤",
    bagFillBadgeMinus = "􀍨",
    bagFillBadgePlus = "􀍦",
    cart = "􀍩",
    cartBadgeMinus = "􀍭",
    cartBadgePlus = "􀍫",
    cartFill = "􀍪",
    cartFillBadgeMinus = "􀍮",
    cartFillBadgePlus = "􀍬",
    creditCard = "􀍯",
    creditCardCircle = "􀒯",
    creditCardCircleFill = "􀒰",
    creditCardFill = "􀍰",
    signature = "􀙤",
}
