export enum Health {
    bandage = "􀎓",
    bandageFill = "􀎔",
    bedDouble = "􀙩",
    bedDoubleFill = "􀙪",
    boltHeart = "􀞽",
    boltHeartFill = "􀛥",
    cross = "􀣜",
    crossCase = "􀯙",
    crossCaseFill = "􀯚",
    crossCircle = "􀣞",
    crossCircleFill = "􀣟",
    crossFill = "􀣝",
    heart = "􀊴",
    heartCircle = "􀊸",
    heartCircleFill = "􀊹",
    heartFill = "􀊵",
    pills = "􀠱",
    pillsFill = "􀠲",
    starOfLife = "􀑆",
    starOfLifeCircle = "􀒺",
    starOfLifeCircleFill = "􀒻",
    starOfLifeFill = "􀑇",
    waveFormPathEcg = "􀜟",
    waveFormPathEcgRectangle = "􀟪",
    waveFormPathEcgRectangleFill = "􀟫",
}
