export enum Transport {
    airplane = "􀑓",
    airplaneCircle = "􀒸",
    airplaneCircleFill = "􀒹",
    bicycle = "􀡥",
    bicycleCircle = "􀱬",
    bicycleCircleFill = "􀱭",
    boltCar = "􀡞",
    boltCarFill = "􀝃",
    bus = "􀝈",
    busDoubleDecker = "􀜛",
    busFill = "􀝉",
    car = "􀙘",
    carTwo = "􀝄",
    carTwoFill = "􀝅",
    carCircle = "􀭯",
    carCircleFill = "􀭰",
    carFill = "􀙙",
    figureWalk = "􀝢",
    figureWalkCircle = "􀝣",
    figureWalkCircleFill = "􀝤",
    figureWave = "􀝻",
    figureWaveCircle = "􀝼",
    figureWaveCircleFill = "􀝽",
    tram = "􀝆",
    tramFill = "􀝇",
    tramTunnelFill = "􀜝",
}
