name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g react-native-cli
          npm install -g detox-cli
      - name: Install Detox
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Install NPM Dependencies
        run: cd template && npm i --f
      - name: Unit Tests
        run: cd template && npm run tests
